### ISSUE TITLE
Support pluggable metrics

### ISSUE THREAD

**Issue by hampelm** [thecarebot/carebot#292]
First stab: team configurations and queries. 

Team configuration (filename is team name, eg `visuals-graphics.yaml`. Each team defines story sources (eg rss, from a spreadsheet) that are automatically ingested. It also defines queries for expected stats (eg scroll-depth, linger-time) that are regularly polled and announced. 

```
channel: "visuals-graphics"
ga_org_id: "100693289"
sources:
  -
    type: "spreadsheet"
    doc_key: "1Gcumd0uOl3eSUvc0y5CWmmHVOKwX609-js5EnE8i3lI"
queries:
  - npr-linger-time
  - npr-scroll-depth
```

Query configuration, filename `npr-linger-time.yaml`. Queries tell the app how to get the stats from Google Analytics (or other systems in the future), how to convert that data into a stat to post, how to set up the chart, and what message to post regularly. 

```
description: "How long someone looked at a graphic"
query:
  filters: ga:eventCategory==%s;ga:eventAction==on-screen;ga:eventLabel==10s,ga:eventLabel==20s,ga:eventLabel==30s,ga:eventLabel==40s,ga:eventLabel==50s,ga:eventLabel==1m,ga:eventLabel==2m,ga:eventLabel==3m,ga:eventLabel==4m,ga:eventLabel==5m,ga:eventLabel==10m
  metrics: "ga:totalEvents"
  dimensions: "ga:eventLabel"
  sort: "-ga:totalEvents"
data: 
  calculate: "median"
  units: "time" 
  column_index: "0"
report:
  message: "The average linger time is %s"
chart:
  labels:
    - "10s"
    - "20s"
    - "30s"
    - "40s"
    - "50s"
    - "1m"
    - "2m"
    - "3m"
    - "4m"
    - "5m+"
  colors:
    - "etc..."
```
